version: "3.7"

services:
  server:
    image: nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        hca.enable: "true"
        hca.min-containers: 2
        hca.max-containers: 10
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
        reservations:
          cpus: "0.2"
          memory: 20M